### ISSUE TITLE
Messaging a player allows white space

### ISSUE THREAD

**Issue by MasonRotMG** [LoESoft-Games/LoE-Realm#31]
![screenshot 351](https://user-images.githubusercontent.com/38711745/40941240-de7b335c-680f-11e8-86e9-5781b67d9b00.png)
This doesn't happen when messaging the world

**Comment by NeverWantedToWork** [comment]
lol nub

**Comment by Devwarlt** [comment]
Thank you @MasonRotMG for report. I will apply a ReGex and text validator into client and server side to avoid that issue.
