### ISSUE TITLE
Attacking 

### ISSUE THREAD

**Issue by kazz2018** [LoESoft-Games/LoE-Realm#32]
no forms of attacking are allowed or not visual 
probably due to no weapons

**Comment by NeverWantedToWork** [comment]
oh, really

**Comment by MasonRotMG** [comment]
Great issue

**Comment by Spacegamer11** [comment]
Let us at least punch so I can be the owner of the server due to amazing punching skill in video games, as that is not currently in so I currently cannot own the infidel and that is considered a feature that must be added in this instant.

**Comment by NeverWantedToWork** [comment]
beat my meat

**Comment by Spacegamer11** [comment]
nou

**Comment by NeverWantedToWork** [comment]
everyone who's reading this is gay

**Comment by Devwarlt** [comment]
There is no combat system yet.
